### ISSUE TITLE
Out of all my assets, only Kenney stuff is detected / listed

### ISSUE THREAD

**Issue by metaleap** [Kaifungamedev/godot_local_assets_browser#2]
Using latest git version, not the old one on Godot's Asset Lib.

So I have this assets folder full of stuff: 

![image](https://github.com/user-attachments/assets/a6fb58a4-c570-4919-bb49-d409db47c84a)

But the Local Assets Browser only recognizes / detects / lists Kenney's stuff, I've carefully scanned the full list even if not fully in the screenshot:

![image](https://github.com/user-attachments/assets/838815b6-f56d-456f-a0b4-442f8e80a1b8)

Any ideas why? Do you require some special files like Preview.png or License.txt or something?

**Comment by Kaifungamedev** [comment]
Hello, first off thanks for trying my asset browser, second most likely the problem is that no image file name matches one of the names in `Editor settings -> Local Assets -> File preview names`, there are three ways you can fix this
1. find a common file preview image name and add it to `Editor settings -> Local Assets -> File preview names`. (eg. all folders under `polyhaven-textures` have an image file named `polyhaven-texture-sample`)
2. create an `Assets.json` file in every folder with your assets (more info in [readme.md](https://github.com/Kaifungamedev/godot_local_assets_browser?tab=readme-ov-file#troubleshooting))
3. turn on `Local_Assets -> use_first_image_found` in the editor settings

**Comment by metaleap** [comment]
Thanks! I chose number 3 and that "solved" it, as in it was showing "Loading" way longer than previously, very long in fact.. blocking the editor GUI while filling up my machine's 32GB RAM right until Godot's editor process insta-died (I assume OOM-killed by kernel, as I was watching this play out in KDE's System Monitor).

For reference, if you wish to attempt to repro that, that `gda` folder at my end is 348GB of some 95k files spread over 22k sub-folders  :grin:  

But that's off-topic for this Issue so feel free to close  =)

**Comment by Kaifungamedev** [comment]
Well I'm glad you got it working (sorta), as the suspeced OOM error is something I'll look into. 😊
